application: dead-channel-news
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /google4c14bfd1bdbab0dd.html
  static_files: static/google4c14bfd1bdbab0dd.html
  upload: static/google4c14bfd1bdbab0dd.html
- url: /static/
  static_dir: static

- url: /cron/hourly
  script: handlers.py
  login: admin
- url: /cron/daily
  script: handlers.py
  login: admin
- url: /list.csv
  script: handlers.py
  login: admin
- url: /notify
  script: handlers.py
  login: admin

- url: /gae-feedback
  script: feedback.py

- url: .*
  script: handlers.py
